version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    environment:
      - JAVA_HOME=/usr/local/sdkman/candidates/java/current
      - GRADLE_HOME=/usr/local/sdkman/candidates/gradle/current
      - PATH=/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5005:5005"  # Java debug port
